# Generated by Django 3.2.5 on 2021-08-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='custom_url',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='yt_id',
        ),
    ]
