# Generated by Django 3.2.5 on 2021-08-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0002_auto_20210804_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='custom_url',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='channel',
            name='url',
            field=models.CharField(default='', max_length=56),
        ),
        migrations.AddField(
            model_name='channel',
            name='yt_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
