# Generated by Django 3.2.5 on 2021-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0004_auto_20210806_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='yt_name',
            new_name='name',
        ),
    ]
