# Generated by Django 3.2.5 on 2021-08-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0005_rename_yt_name_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='upper_name',
        ),
    ]
