# Generated by Django 3.2.5 on 2021-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0006_remove_channel_upper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='upper_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
