# Generated by Django 3.2.5 on 2021-08-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0007_channel_upper_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_value', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(verbose_name='update date')),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTStats.channel')),
            ],
        ),
    ]
