# Generated by Django 3.2.5 on 2021-09-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0011_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='update_date',
            field=models.DateTimeField(default=None, verbose_name='update date'),
        ),
    ]
