# Generated by Django 3.2.5 on 2021-09-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0013_auto_20210906_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
