# Generated by Django 3.2.5 on 2021-09-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YTStats', '0014_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_youtube_id', models.CharField(max_length=11)),
                ('video_views', models.IntegerField(default=0)),
                ('video_likes', models.IntegerField(default=0)),
                ('video_dislikes', models.IntegerField(default=0)),
                ('video_comments', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(verbose_name='update date')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTStats.channel')),
            ],
        ),
    ]
